language: python

python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - 3.4
  - 3.5
  - 3.5-dev
  - nightly

before_install:
  - sudo apt-get install -qq autoconf libcurl4-openssl-dev automake libtool

install:
  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install unittest2; fi
  - ./.travis.libucl.sh

script:
  - python setup.py test
